=head1 AnoNet2 Links

Back to homepage - L<http://www.anonet2.org/>

This is a collection of links that you may find interesting:

20110221 - L<"Piracy Has All But Dismantled Our Recorded Music Industry"|http://torrentfreak.com/piracy-has-all-but-dismantled-our-recorded-music-industry-110217/>

20110221 - L<U.S. Government Shuts Down 84,000 Websites, `By Mistake'|http://torrentfreak.com/u-s-government-shuts-down-84000-websites-by-mistake-110216/>

20101026 - L<http://www.privacy.net/> (L<direct link to a web browser privacy test|http://analyze.privacy.net/test.asp?RequestCookies=&Requestdate=&refer=http://network-tools.com/analyze/>)

20101024 - L<http://abcnews.go.com/2020/Stossel/story?id=4400537&page=1>

20101024 - L<https://financialcryptography.com/mt/archives/001081.html>

20101024 - L<http://www.truthdig.com/report/item/20080727_the_military_industrial_complex_its_much_later_than_you_think/>

20101024 - L<http://www.unlinq.com/> (anonymous credit cards)

20100819 - L<http://www.networkworld.com/community/node/64181>

20100819 - L<https://www.eff.org/press/archives/2010/04/13>

20100818 - L<http://www.networkworld.com/community/node/64074>

20100720 - L<http://www.wired.com/politics/security/commentary/securitymatters/2006/05/70886> (thanks L<http://darknet.me/privacy.html>)

20100518 - L<http://torrentfreak.com/damned-pirates-hollywood-sets-10-billion-box-office-record-091211/>

20100518 - L<http://torrentfreak.com/mpaa-and-riaa-call-for-copyright-police-state-100415/>

20100514 - L<http://www.theregister.co.uk/2010/04/30/bittorrent_continuous_spying/>

20100430 - L<http://www.truthdig.com/report/item/20080727_the_military_industrial_complex_its_much_later_than_you_think/>
