=head1 AnoNet2 Links

Back to homepage - L<http://www.anonet2.org/>

This is a collection of links that you may find interesting:

20111124 - L<Document Trove Exposes Surveillance Methods|http://online.wsj.com/article/SB10001424052970203611404577044192607407780.html>

20111123 - L<Greek crisis demonstrates that Europe has no clothes|http://fullcomment.nationalpost.com/2011/11/04/greek-crisis-demonstrates-that-europe-has-no-clothes/>

20111123 - L<Why you should always encrypt your smartphone|http://arstechnica.com/gadgets/guides/2011/01/why-you-should-always-encrypt-your-smartphone.ars/2>

20111123 - L<The gadgets police use to snarf cell phone data|http://arstechnica.com/tech-policy/news/2011/04/michigan-state-police-we-only-grab-your-cellphone-data-with-a-warrant.ars>

20111123 - L<Cellebrite UFED Extends Forensic Capabilities to Android Mobile Devices|http://www.prnewswire.com/news-releases/cellebrite-ufed-extends-forensic-capabilities-to-android-mobile-devices-132449788.html>

20111122 - L<Blocking DNS|http://www.isc.org/community/blog/201103/blocking-dns>

20111009 - L<Chaos Computer Club analyzes government malware|http://ccc.de/en/updates/2011/staatstrojaner>

20110902 - L<Apple Cries About Samsung and Motorola's Patent "Monopoly"|http://www.dailytech.com/Apple+Cries+About+Samsung+and+Motorolas+Patent+Monopoly/article22586.htm>

20110902 - L<Apple Scores Meaningless Dutch Court Victory Against Samsung|http://www.osnews.com/story/25098/Apple_Scores_Meaningless_Dutch_Court_Victory_Against_Samsung>

20110825 - L<CERN 'gags' physicists in cosmic ray climate experiment|http://www.theregister.co.uk/2011/07/18/cern_cosmic_ray_gag/print.html>

20110825 - L<Social networks likely to snub Home Office in riot confab|http://www.theregister.co.uk/2011/08/25/home_office_social_networks_england_riots/>

20110822 - L<The Community Design: ...and you Thought the USPTO Was Bad|http://www.osnews.com/story/25056/The_Community_Design_and_you_Thought_the_USPTO_Was_Bad/page1/>

20110822 - L<Apple Also Manipulated Evidence in Dutch Apple v Samsung Case|http://www.osnews.com/story/25087/Apple_Also_Manipulated_Evidence_in_Dutch_Apple_v_Samsung_Case>

20110822 - L<Why Samsung was not put on notice before the European Galaxy Tab 10.1 injunction was ordered|http://fosspatents.blogspot.com/2011/08/why-samsung-was-not-put-on-notice.html>

20110816 - L<Apple changed shape of Galaxy Tab in court filing|http://www.theregister.co.uk/2011/08/16/apple_samsung/>

20110814 - L<Should access to Twitter and Facebook be curbed when they're used to plot crime?|http://www.cbc.ca/news/yourcommunity/2011/08/should-access-to-twitter-and-facebook-be-curbed-when-theyre-used-to-plot-crime.html>

20110813 - L<Microsoft bans open source license trio from WinPhone|http://www.theregister.co.uk/2011/02/17/microsoft_bans_opensource_windows_phone/>

20110813 - L<Google lands patent for, um, estimating shipment time|http://www.theregister.co.uk/2011/08/12/google_customer_notification_patent/>

20110729 - L<UK Cops 'duped' into arresting wrong LulzSec suspect|http://www.theregister.co.uk/2011/07/28/topiary_arrest_rumor/>

20110729 - L<Pwned HBGary boss cancels public debate after legal threats|http://www.theregister.co.uk/2011/07/28/ex_hbgary_boss_cancels_blackhat_gig/>

20110728 - L<Film studios thrash BT in Newzbin site-block test case|http://www.theregister.co.uk/2011/07/28/site_blocking_bt_and_newzbin2/>

20110708 - L<Copyright alert system planned by studios, ISPs|http://www.cbc.ca/news/technology/story/2011/07/08/copyright-warnings.html>

20110705 - L<Afghans Build Open-Source Internet From Trash|http://www.shareable.net/blog/afghans-build-open-source-internet-from-trash-0>

20110605 - L<Sharing That Music Subscription Login Could Put You In Jail|http://torrentfreak.com/sharing-that-music-subscription-login-could-put-you-in-jail-110603/>

20110605 - L<IFPI's child porn strategy|http://christianengstrom.wordpress.com/2010/04/27/ifpis-child-porn-strategy/>

20110524 - L<CPS: We won't prosecute over BT/Phorm secret trials|http://www.theregister.co.uk/2011/04/08/cps_no_prosecution_over_bt_phorm/>

20110524 - L<BT cheerfully admits snooping on customer LANs|http://www.theregister.co.uk/2011/05/24/bt_snooping/>

20110523 - L<The Day I Infringed My Own Copyright|http://waveformless.blogspot.com/2010/03/day-i-infringed-my-own-copyright.html>

20110228 - L<HP Dragnet Grabbed 9 Reporters|http://www.wired.com/politics/security/news/2006/09/71749>

20110221 - L<"Piracy Has All But Dismantled Our Recorded Music Industry"|http://torrentfreak.com/piracy-has-all-but-dismantled-our-recorded-music-industry-110217/>

20110221 - L<U.S. Government Shuts Down 84,000 Websites, `By Mistake'|http://torrentfreak.com/u-s-government-shuts-down-84000-websites-by-mistake-110216/>

20101026 - L<http://www.privacy.net/> (L<direct link to a web browser privacy test|http://analyze.privacy.net/test.asp?RequestCookies=&Requestdate=&refer=http://network-tools.com/analyze/>)

20101024 - L<http://abcnews.go.com/2020/Stossel/story?id=4400537&page=1>

20101024 - L<https://financialcryptography.com/mt/archives/001081.html>

20101024 - L<http://www.truthdig.com/report/item/20080727_the_military_industrial_complex_its_much_later_than_you_think/>

20101024 - L<http://www.unlinq.com/> (anonymous credit cards)

20100819 - L<http://www.networkworld.com/community/node/64181>

20100819 - L<https://www.eff.org/press/archives/2010/04/13>

20100818 - L<http://www.networkworld.com/community/node/64074>

20100720 - L<http://www.wired.com/politics/security/commentary/securitymatters/2006/05/70886> (thanks L<http://darknet.me/privacy.html>)

20100518 - L<http://torrentfreak.com/damned-pirates-hollywood-sets-10-billion-box-office-record-091211/>

20100518 - L<http://torrentfreak.com/mpaa-and-riaa-call-for-copyright-police-state-100415/>

20100514 - L<http://www.theregister.co.uk/2010/04/30/bittorrent_continuous_spying/>

20100430 - L<http://www.truthdig.com/report/item/20080727_the_military_industrial_complex_its_much_later_than_you_think/>
