=head1 AnoNet2 Links

Back to homepage - L<http://www.anonet2.org/>

This is a collection of links that you may find interesting:

20100518 - L<http://torrentfreak.com/damned-pirates-hollywood-sets-10-billion-box-office-record-091211/>

20100518 - L<http://torrentfreak.com/mpaa-and-riaa-call-for-copyright-police-state-100415/>

20100514 - L<http://www.theregister.co.uk/2010/04/30/bittorrent_continuous_spying/>

20100430 - L<http://www.truthdig.com/report/item/20080727_the_military_industrial_complex_its_much_later_than_you_think/>
