#!/bin/sh
git add configure db doc git-commit gitd scripts contrib .gitignore
TZ=UTC git commit --date="`date -u +'%s'`"
test -x /usr/lib/git-core/git-update-server-info && /usr/lib/git-core/git-update-server-info
