#!/usr/bin/python
import SimpleHTTPServer
import SocketServer

PORT = 8053

Handler = SimpleHTTPServer.SimpleHTTPRequestHandler
httpd = SocketServer.TCPServer(("", PORT), Handler)
httpd.serve_forever()
