#!/bin/bash
#Remember to redirect the output into some file!

sh scripts/check_db_safety || exit 1

for tld in $(ls db/dom/); do 
	for domain in $(ls db/dom/${tld}/); do 
		for ns in $(cat db/dom/${tld}/${domain}/ns/*); do 
			STR="server=/${domain}.${tld}/${ns}"
			if [ "$(grep $STR /etc/dnsmasq.conf)" = "" ]; then
				echo $STR
			fi
		done; 
	done; 
done
