#!/bin/sh
(
 if [ x"$USE_BC" = x1 ]; then
  echo -n "ibase=16; "
 fi
 if [ x"$1" = x ]; then
  cat
 else
  echo "$1"
 fi
) | (
 if [ x"$USE_BC" = x1 ]; then
  bc -q
 else
  cat ./scripts/hex2dec.d/"$(cat)"
 fi
)
