#!/usr/bin/env python

'''
       This currently does nothing
       When its finished you will
       be able to brute force IRC
       nicksrv.
                                  '''

from time import sleep
from socket import *
import sys
s=socket(AF_INET,SOCK_STREAM)
s.connect((sys.argv[1],int(sys.argv[2])))
s.send('NICK '+sys.argv[3]+'\r\n')
sleep(5)
